name: ooi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - argcomplete
  - beautifulsoup4
  - bottleneck
  - cgsn_parsers
  - chest
  - conda-build
  - configobj
  - dask
  - erddapy
  - flox
  - geos
  - gsw
  - hdf4
  - h5netcdf
  - ioos_qc
  - jupyterlab
  - libnetcdf
  - matplotlib
  - munch>=2.1.0
  - netcdf4
  - nodejs
  - nose
  - numexpr
  - numpy
  - pip
  - pocean-core
  - pyasn1
  - pyaxiom
  - pygc
  - pyIGRF
  - pyncml
  - pytz
  - pysolar
  - pyYAML
  - scipy
  - simplejson
  - sockjs-tornado
  - tqdm
  - xarray
  - xlrd
  - yaml
  - pip:
    - https://bitbucket.org/ooicgsn/pyseas/get/develop.zip
    - https://bitbucket.org/ooicgsn/cgsn-processing/get/master.zip
